### ISSUE TITLE
Tolerance to server failures

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx-matlab#12]
When the server is unavailable, REST messages that could not be delivered should be saved locally instead of being lost. They would be sent again later automatically.

* Implement a queue with messages that could not be delivered. Use e.g. `~/.alyx/rest-queue/2017-05-09-17-28-24.put.json` where every file is a message.
* Whenever a REST API call is done, the queue is flushed first: we try to send all existing messages in the queue. As soon as a message is sent, the corresponding file is deleted.
* Whenever a REST API call fails, the message is saved in the queue as a JSON file.

**Comment by nsteinme** [comment]
It may make even more sense to do it the other way around: when you call the rest API, first write the new message to the queue, then flush the queue. This way you're sure the queueing/flushing thing is always working.

**Comment by kdharris101** [comment]
Agreed.

One minor point: if I understand correctly, ~/.alyx/rest-queue/ will be in the user’s home directory. This means that if the db goes down and then the user logs out, the additional messages won’t get uploaded until they log back in.

I think we discussed this earlier, and Nick raised how our current machines all run from a single account. So I guess it is moot for now – but still is there any reason not to have a single location for all users?

Last point: do we need to worry about this being cross-platform on the client side? I.e. do some of the data acquisition machines run linux, or are they all windows?

**Comment by nsteinme** [comment]
Good question, but they are all windows so for now we can assume that.

**Comment by kdharris101** [comment]
Thanks. Even though it is not yet necessary, for future proofing I think we should


1.       Make it use a single location for all users

2.       Make this cross-platform

I don’t actually know how to do this however!

**Comment by rossant** [comment]
No problem with (1). As for (2) it's easy to write cross-platform code in Python but in Matlab I have no idea.

**Comment by kdharris101** [comment]
If it is just about file names and paths, will this be sufficient?

https://uk.mathworks.com/help/matlab/ref/fullfile.html

**Comment by rossant** [comment]
Yes I think so! Then it is a matter of

* listing all files in a directory
* filtering by file extension (e.g. `*.put.json` or `*.post.json`)
* reading/writing a file

**Comment by nsteinme** [comment]
Yes, for that you want the dir command:

>> myDirList = dir(fullfile(myQdir, '*.put.json'))

Also I should have remembered sooner, there is a lot of local
just-in-case-zserver-doesn't-work storage going on with our normal data
acquisition code, which generally uses C:/LocalExpData. That's given by
p.localRepository here
<https://github.com/cortex-lab/Rigbox/blob/master/%2Bdat/paths.m>. You
could actually call dat.paths and use localRepository, in case someone has
overloaded that function with different paths (that's the intended usage).

**Comment by rossant** [comment]
Something like this should do it (pseudocode):

```
function postData()
  jsonData = savejson('', data);
  savetofile(jsonData, fullfile(queueDir, "$dateHour.post.json"));
  flushQueue();

function putData()
  % idem

function flushQueue()
  files = dir(fullfile(queueDir, "*.post.json"))
  for file in files:
    jsonData = loadjson(file)
    fullEndpoint = alyx.makeEndpoint(alyxInstance, endpoint);
    ... % copy code from postData.m

  files = dir(fullfile(queueDir, "*.put.json"))
  for file in files:
    jsonData = loadjson(file)
    fullEndpoint = alyx.makeEndpoint(alyxInstance, endpoint);
    ... % copy code from putData.m
```

If ever you're willing to convert this to proper Matlab it would be with great pleasure, I'm sure you would be 10x faster than me! :)

**Comment by nsteinme** [comment]
This looks great, I'll try to find someone to do it at today's meeting.
Thanks!

**Comment by nippoo** [comment]
It's not obvious to find a directory which is writable to all users without explicitly creating it as an administrator. I'm not sure such a directory exists apart from perhaps C:/Windows/Temp but that has its own problems.

**Comment by nippoo** [comment]
Linux certainly doesn't have anything user-writable by default except /tmp and ~

**Comment by kdharris101** [comment]
We can create such a directory once as administrator on each computer

E.g. /var/alyx

Sent from my iPhone

On May 10, 2017, at 4:42 PM, Max Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


Linux certainly doesn't have anything user-writable by default except /tmp and ~

**Comment by petersaj** [comment]
I just added a queuing system to the alyx-matlab repository code. Things to note: 

- I defined the local queue directories in alyx.queueConfig, currently it's empty for macs and unix since I didn't know what works on those operating systems
- the queue is flushed on alyx.postData, alyx.putData, and alyx.getToken
- if the computer becomes disconnected from the internet I don't think this will work because alyx.getToken will fail, but it requires a token to execute alyx.makeEndpoint, maybe something to keep in mind

**Comment by kdharris101** [comment]
Thanks Andy!

**Comment by nsteinme** [comment]
Yes, thanks! If I understand your last point, would it make sense to put
the alyx.makeEndpoint call into the flushQueue function rather than into
the postData/putData functions? So it would just be writing the relative
endpoint to the queue file, if you had only supplied a relative endpoint.
Is there a drawback to this, and does it solve what you were pointing out?

**Comment by petersaj** [comment]
yup - that would only matter if the baseURL changed while things were down, but that's probably not something to worry about. changed things around so now it's robust to 1) the internet never having been connected and 2) the internet going out after making a token for Alyx. In the case of 1, you can call post/putData with an empty variable as your alyxInstance if you want, so that would have to be accounted for wherever those functions are used

**Comment by nsteinme** [comment]
@petersaj did this; closing. One minor thing we didn't decide about or resolve, is whether the MC/Rigbox code could/should be trying to post everything to alyx whether anyone has logged in or not. Currently it won't try unless you're logged in, but with the queue it could just go ahead anyway. Something to keep in mind.
