### ISSUE TITLE
Alyx not posting weights after login

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx-matlab#21]
I recorded a weight before logging into Alyx.  The log states that the weight will be posted after login, however it didn't.  There are no visible errors and all other postings (those after logging in) have succeeded.

**Comment by petersaj** [comment]
sounds like might be a queuing error - can you come grab me when we're both
free and I'll check it out?

**Comment by nsteinme** [comment]
No this is just a thing I tried to implement before we came up with the queuing idea - it didn't work for some reason and I never had time to debug. In any case, you should login if you want stuff posted for now - otherwise we can work out a thing where it's posting everything regardless of login via queuing but it'll require more work.
