### ISSUE TITLE
All subjects shown in subject drop-down

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx-matlab#22]
For one reason or another the subject drop-downs are now populated with a list of all mice, instead of only the water restricted ones.  If this was deliberate, could we please go back to the restricted list, or at least have a filter button next to the drop-down?

**Comment by nsteinme** [comment]
@k1o0 let me know if this isn't fixed tomorrow - @rossant should have
resolved this, I think, depending on what exactly the issue was. Fwiw the
list has always been "all alive mice not in stock" - and of course this is
intentionally not just water restricted mice since people do lots of
experiments with non-water-restricted mice in the lab.

**Comment by rossant** [comment]
Where is the code for this? Could you try running the REST URL directly in the browser to test?

**Comment by nsteinme** [comment]
Yes I think this is working now. @k1o0 closing for now, re-open if I didn't understand the issue.
