### ISSUE TITLE
Running experiments when Alyx is down

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx-matlab#31]
So at the moment Alyx will try to log in at every stage and will throw an error if the log in fails.  Perhaps we should have a flag to the object that is set when the server becomes inaccessible?  Now that Alyx is an object this should be trivial.  When set, Alyx wouldn't bother to get data or flush the queue.  The flag could either have a get method that pings the server or simple is set when jsonPost returns a 501.  Any thoughts?

**Comment by rossant** [comment]
In the upcoming Python client I do something like this:

* Make the request with the cached token
* If the status code is 403, try to get a new token and try again
* If the request fails for whatever reason, raise an error or (in your case) save the request to the queue (which actually happens in all cases, I believe)
* Otherwise, return the response

Could you do something like this too? Why is it a problem if the client tries to connect, fails, and shows an error? The requests are all saved in a queue anyway, right?

If we add some sort of a flag, we have to decide how we disable it once Alyx is up again. How would the client know when the server is up again if it doesn't try to connect anymore?

**Comment by k1o0** [comment]
Currently a 3xx or 4xx status leads to deletion of the offending post.  Only 5xx status codes are kept in the queue...

**Comment by petersaj** [comment]
that was because of Max's advice, copied below:

200 error codes are all successes so nothing needs to be queued
300 error codes shouldn't be queued. They're redirects
400 error codes must not be queued either - they're supposed to indicate a
user error (wrong type of data, no endpoint available blah blah blah)
500 error codes *should* normally be queued as they indicate a server error.

In essence I'd check for a 5xx code (probably not a 511 but we're not using
those yet) or a network timeout. But don't queue in case of 3xx or 4xx
codes.

**Comment by k1o0** [comment]
When tokens start expiring I think it's a good idea to re-prompt the user to log in (except for on expServer, where it should request a new instance from mc), otherwise the posts will be needlessly lost.  Currently there's not really any other reason for a token to be invalid.

**Comment by rossant** [comment]
OK sounds good. If the server is unresponsive, the message is queued too, right?

**Comment by k1o0** [comment]
Right.  I've made the relevant changes.
