### ISSUE TITLE
Subject History and Water History mismatch- Alyx and Matlab GUI

### ISSUE THREAD

**Issue by laurax452** [cortex-lab/alyx-matlab#39]
There are a few inconsistencies between alyx and the Matlab GUI for weighing and water administration see attached photos for an extreme version. (mouse mmm006)
![mmm006](https://user-images.githubusercontent.com/27958601/53155719-8d733080-35b5-11e9-91c2-f33eea04c31a.png)
![mvimg_20190219_133735](https://user-images.githubusercontent.com/27958601/53155732-9237e480-35b5-11e9-85c1-8bfd42a6a246.jpg)

As you can see there are large differences in the weight percentage. PILs are emailed on the basis of (I think) Alyx figures, but trainers (often) use the subject history from the Matlab GUI to keep the mice above 80%. This needs fixing as many of us are struggling to keep 'healthy looking' mice above 80% and it would be nice to know which graphs to believe.

In addition there are slight inconsistencies between water required in the subject history panel and the GUI itself (usually around 0.01ml) I presume these are rounding errors but it would be good to know which one I should adhere to. Different people use either Alyx, the GUI or the subject history of the GUI to administer water, whilst the differences are very small it would be good if this could be standardised across the platforms (low priority)

**Comment by charureddy** [comment]
Miles has figured out why this is happening:

''For some of these dates (e.g. 19.02.19) there are multiple weight records.  On the Alyx admin interface the last recorded weight is used to calculate the percent weight for that day (even if the mouse hasn't been weighed that day).  In the MATLAB code the first weight of that day is used (the field is empty if the mouse hasn't been weighed that day).  
I can change this behaviour, however I'd prefer to leave it as it is as on occasion people weigh their mice after training/giving water.  
It's important to change your weight record on Alyx if you make an incorrect weighing, rather than leaving it and submitting a new weight.  You can easily change it by logging in and clicking on the weight record in the actions list''.

**Comment by rossant** [comment]
should something be changed in Alyx then?

**Comment by k1o0** [comment]
@rossant No, we discussed it and I'll change the client code.

**Comment by k1o0** [comment]
Created an issue here too so that it can be tracked with the main code changes: https://github.com/cortex-lab/Rigbox/issues/114

Importantly this won't be implemented until I've written some general tests.  You can track that progress here: https://github.com/cortex-lab/alyx-matlab/issues/41
